[project]
name = "nix"
revision = "1.0"

[providers]
devenv = "bws://885d83f3-063b-4ba7-bddc-b45a00fd59b9"

[profiles.development]
FIRECRAWL_API_KEY = { description = "Firecrawl API key", required = true, providers = [
  "devenv"
] }
DEEPSEEK_API_KEY = { description = "DeepSeek API key", required = false, providers = [
  "devenv"
] }
OPENROUTER_API_KEY = { description = "OpenRouter API key", required = true, providers = [
  "devenv"
] }

# [profiles.development.defaults]
# providers = ["devenv"]
